# This YAML file configures Travis CI to test the Spring Boot application.

language: java

notifications:
  email:
    on_success: change
    on_failure: always
  slack: jleung-services:uoE4cCbtpfyBZkeYFLaOC3if
